namespace ASC.People.Mapping.TypeConverters;

public class EmployeeTypeConverter : ITypeConverter<UserInfo, EmployeeDto>, ITypeConverter<UserInfo, EmployeeFullDto>
{
    private readonly UserPhotoManager _userPhotoManager;
    private readonly ApiDateTimeHelper _apiDateTimeHelper;
    private readonly ApiContext _httpContext;
    private readonly DisplayUserSettingsHelper _displayUserSettingsHelper;
    private readonly CommonLinkUtility _commonLinkUtility;
    private readonly UserManager _userManager;
    private readonly ApiContext _apiContext;

    public EmployeeFullDto Convert(UserInfo source, EmployeeFullDto destination, ResolutionContext context)
    {
        var result = new EmployeeFullDto
        {
            UserName = source.UserName,
            FirstName = source.FirstName,
            LastName = source.LastName,
            Birthday = _apiDateTimeHelper.Get(source.BirthDate),
            Status = source.Status,
            ActivationStatus = source.ActivationStatus & ~EmployeeActivationStatus.AutoGenerated,
            Terminated = _apiDateTimeHelper.Get(source.TerminatedDate),
            WorkFrom = _apiDateTimeHelper.Get(source.WorkFromDate),
            Email = source.Email,
            IsVisitor = source.IsVisitor(_userManager),
            IsAdmin = source.IsAdmin(_userManager),
            IsOwner = source.IsOwner(_apiContext.Tenant),
            IsLDAP = source.IsLDAP(),
            IsSSO = source.IsSSO()
        };
    }

    public EmployeeDto Convert(UserInfo source, EmployeeDto destination, ResolutionContext context)
    {
        var result = new EmployeeDto();

        result.Id = source.ID;
        result.DisplayName = _displayUserSettingsHelper.GetFullUserName(source);

        if (!string.IsNullOrEmpty(source.Title))
        {
            result.Title = source.Title;
        }

        var userInfoLM = source.LastModified.GetHashCode();

        if (_httpContext.Check("avatarSmall"))
        {
            result.AvatarSmall = _userPhotoManager.GetSmallPhotoURL(source.ID, out var isdef)
                + (isdef ? "" : $"?_={userInfoLM}");
        }

        if (result.Id != Guid.Empty)
        {
            var profileUrl = _commonLinkUtility.GetUserProfile(source, false);
            result.ProfileUrl = _commonLinkUtility.GetFullAbsolutePath(profileUrl);
        }

        return result;
    }
}
