namespace ASC.Api.Core.Mapping;

[Scope]
public class EmployeeTypeConverter : ITypeConverter<UserInfo, EmployeeDto>, ITypeConverter<UserInfo, EmployeeFullDto>
{
    private readonly UserPhotoManager _userPhotoManager;
    private readonly DisplayUserSettingsHelper _displayUserSettingsHelper;
    private readonly CommonLinkUtility _commonLinkUtility;
    private readonly ApiContext _apiContext;
    private readonly WebItemSecurity _webItemSecurity;
    private readonly UserManager _userManager;
    private readonly ApiDateTimeHelper _apiDateTimeHelper;

    public EmployeeTypeConverter(
        UserPhotoManager userPhotoManager,
        ApiContext apiContext,
        DisplayUserSettingsHelper displayUserSettingsHelper,
        CommonLinkUtility commonLinkUtility,
        UserManager userManager,
        ApiDateTimeHelper apiDateTimeHelper,
        WebItemSecurity webItemSecurity)
    {
        _userPhotoManager = userPhotoManager;
        _apiContext = apiContext;
        _displayUserSettingsHelper = displayUserSettingsHelper;
        _commonLinkUtility = commonLinkUtility;
        _userManager = userManager;
        _apiDateTimeHelper = apiDateTimeHelper;
        _webItemSecurity = webItemSecurity;
    }

    public EmployeeDto Convert(UserInfo source, EmployeeDto destination, ResolutionContext context)
    {
        var result = new EmployeeDto();

        InternalConvert(source, result);

        return result;
    }

    public EmployeeFullDto Convert(UserInfo source, EmployeeFullDto destination, ResolutionContext context)
    {
        var result = new EmployeeFullDto
        {
            UserName = source.UserName,
            FirstName = source.FirstName,
            LastName = source.LastName,
            Birthday = _apiDateTimeHelper.Get(source.BirthDate),
            Status = source.Status,
            ActivationStatus = source.ActivationStatus & ~EmployeeActivationStatus.AutoGenerated,
            Terminated = _apiDateTimeHelper.Get(source.TerminatedDate),
            WorkFrom = _apiDateTimeHelper.Get(source.WorkFromDate),
            Email = source.Email,
            IsVisitor = source.IsVisitor(_userManager),
            IsAdmin = source.IsAdmin(_userManager),
            IsOwner = source.IsOwner(_apiContext.Tenant),
            IsLDAP = source.IsLDAP(),
            IsSSO = source.IsSSO()
        };

        InternalConvert(source, result);

        if (source.Sex.HasValue)
        {
            result.Sex = source.Sex.Value ? "male" : "female";
        }

        if (!string.IsNullOrEmpty(source.Location))
        {
            result.Location = source.Location;
        }

        if (!string.IsNullOrEmpty(source.Notes))
        {
            result.Notes = source.Notes;
        }

        if (!string.IsNullOrEmpty(source.MobilePhone))
        {
            result.MobilePhone = source.MobilePhone;
        }

        result.MobilePhoneActivationStatus = source.MobilePhoneActivationStatus;

        if (!string.IsNullOrEmpty(source.CultureName))
        {
            result.CultureName = source.CultureName;
        }

        FillConacts(result, source);

        if (_apiContext.Check("groups") || _apiContext.Check("department"))
        {
            var groups = context.Mapper.Map<List<ASC.Core.Users.GroupInfo>, List<GroupSummaryDto>>(
                _userManager.GetUserGroups(source.ID));

            if (groups.Count > 0)
            {
                result.Groups = groups;
                result.Department = string.Join(", ", result.Groups.Select(d => d.Name.HtmlEncode()));
            }
            else
            {
                result.Department = "";
            }
        }

        var userInfoLM = source.LastModified.GetHashCode();

        if (_apiContext.Check("avatarMax"))
        {
            result.AvatarMax = _userPhotoManager.GetMaxPhotoURL(source.ID, out var isdef) + (isdef ? "" : $"?_={userInfoLM}");
        }

        if (_apiContext.Check("avatarMedium"))
        {
            result.AvatarMedium = _userPhotoManager.GetMediumPhotoURL(source.ID, out var isdef) + (isdef ? "" : $"?_={userInfoLM}");
        }

        if (_apiContext.Check("avatar"))
        {
            result.Avatar = _userPhotoManager.GetBigPhotoURL(source.ID, out var isdef) + (isdef ? "" : $"?_={userInfoLM}");
        }

        if (_apiContext.Check("listAdminModules"))
        {
            var listAdminModules = source.GetListAdminModules(_webItemSecurity);
            if (listAdminModules.Count > 0)
            {
                result.ListAdminModules = listAdminModules;
            }
        }

        return result;
    }

    private void FillConacts(EmployeeFullDto employeeWraperFull, UserInfo userInfo)
    {
        if (userInfo.ContactsList == null)
        {
            return;
        }

        var contacts = new List<Contact>();

        for (var i = 0; i < userInfo.ContactsList.Count; i += 2)
        {
            if (i + 1 < userInfo.ContactsList.Count)
            {
                contacts.Add(new Contact(userInfo.ContactsList[i], userInfo.ContactsList[i + 1]));
            }
        }

        if (contacts.Count > 0)
        {
            employeeWraperFull.Contacts = contacts;
        }
    }

    private EmployeeDto InternalConvert(UserInfo userInfo, EmployeeDto employeeDto)
    {
        employeeDto.Id = userInfo.ID;
        employeeDto.DisplayName = _displayUserSettingsHelper.GetFullUserName(userInfo);

        if (!string.IsNullOrEmpty(userInfo.Title))
        {
            employeeDto.Title = employeeDto.Title;
        }

        var userInfoLM = userInfo.LastModified.GetHashCode();

        if (_apiContext.Check("avatarSmall"))
        {
            employeeDto.AvatarSmall = _userPhotoManager.GetSmallPhotoURL(userInfo.ID, out var isdef)
                + (isdef ? "" : $"?_={userInfoLM}");
        }

        if (employeeDto.Id != Guid.Empty)
        {
            var profileUrl = _commonLinkUtility.GetUserProfile(userInfo, false);
            employeeDto.ProfileUrl = _commonLinkUtility.GetFullAbsolutePath(profileUrl);
        }

        return employeeDto;
    }
}
